

GET http://localhost:8080/users

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "Dario",
    "password": "password-di-dario"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "Mario",
    "password": "password-di-mario"
}

###

GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzYzMjQzMDI4LCJleHAiOjE3NjMyNDMwNDN9.yZ5qOLK8wQYIIgwrbRcroOsHWyxcQ9Li_GaSGBsaDvU

###

POST http://localhost:8080/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzYzMjQzMzIwLCJleHAiOjE3NjM4NDgxMjB9.SSXpRPwEwukLLDfLVdv52ImQf_qi8kGcwSOGLYE565E"
}


###

DELETE http://localhost:8080/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzYzMjQzMzIwLCJleHAiOjE3NjM4NDgxMjB9.SSXpRPwEwukLLDfLVdv52ImQf_qi8kGcwSOGLYE565E"
}