

GET http://localhost:8080/users

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "aaa",
    "password": "@A123456",
    "description": "Descrizione del fantasma di gario",
    "pfp": 10,
    "name": "aaa",
    "email": "aaa@gmail.com"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "aaa",
    "password": "@A123456"
}

###

GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzYzMjQzMDI4LCJleHAiOjE3NjMyNDMwNDN9.yZ5qOLK8wQYIIgwrbRcroOsHWyxcQ9Li_GaSGBsaDvU

###

POST http://localhost:8080/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxNywiaWF0IjoxNzY1NzM5MDA5LCJleHAiOjE3NjYzNDM4MDl9._rth7IF1wHaQCvoz-AqlXhlS5RkCz7HOdM0dEkAUlkc"
}


###

DELETE http://localhost:8080/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzYzMjQzMzIwLCJleHAiOjE3NjM4NDgxMjB9.SSXpRPwEwukLLDfLVdv52ImQf_qi8kGcwSOGLYE565E"
}

###

GET http://localhost:8080/profile/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxNywiaWF0IjoxNzY1NzM5MDIwLCJleHAiOjE3NjU3MzkwMzV9.BUjG8JaI_bRA5rOZM4XagsjP5cobgCf6jYq_Mnxuzu4

###

GET http://localhost:8080/profile/test

###
POST http://localhost:8080/session/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxNywiaWF0IjoxNzY1NzM5MDIwLCJleHAiOjE3NjU3MzkwMzV9.BUjG8JaI_bRA5rOZM4XagsjP5cobgCf6jYq_Mnxuzu4
Content-Type: application/json

{
    "title": "prova"
}