
  create table "public"."app_data" (
    "id" bigint generated by default as identity not null,
    "last_stat_calc" timestamp with time zone
      );



  create table "public"."profile" (
    "id_profile" integer generated by default as identity not null,
    "name" text,
    "description" text,
    "pfp" smallint,
    "id_user" integer not null
      );



  create table "public"."session_segment" (
    "id_session_segment" integer generated by default as identity not null,
    "start_date_time" text,
    "end_date_time" text,
    "id_study_session" integer not null,
    "id_profile" integer,
    "id_topic" integer
      );



  create table "public"."stats" (
    "id_stats" integer generated by default as identity not null,
    "total_hours" numeric,
    "daily_average" numeric,
    "today_hours" numeric,
    "day_streak" smallint,
    "best_day" text,
    "id_profile" integer not null
      );



  create table "public"."study_session" (
    "id_study_session" integer generated by default as identity not null,
    "study_time" numeric not null,
    "title" text not null,
    "start_date_time" timestamp with time zone not null,
    "end_date_time" timestamp with time zone,
    "id_profile" integer not null
      );



  create table "public"."subject" (
    "id_subject" integer generated by default as identity not null,
    "name" text not null,
    "id_profile" integer not null
      );



  create table "public"."subject_stats" (
    "study_time" text not null,
    "id_subject" integer not null,
    "id_profile" integer not null
      );



  create table "public"."topic" (
    "id_topic" integer generated by default as identity not null,
    "name" text,
    "id_subject" integer
      );



  create table "public"."topic_stats" (
    "id_profile" integer not null,
    "id_topic" integer not null,
    "study_time" text
      );



  create table "public"."userinfo" (
    "id_user" integer generated by default as identity not null,
    "username" text not null,
    "email" text not null,
    "password" text not null,
    "fcm_token" text not null,
    "created_on" text not null
      );


CREATE UNIQUE INDEX app_data_pkey ON public.app_data USING btree (id);

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (id_profile);

CREATE UNIQUE INDEX session_segment_pkey ON public.session_segment USING btree (id_session_segment);

CREATE UNIQUE INDEX stats_pkey ON public.stats USING btree (id_stats);

CREATE UNIQUE INDEX study_session_pkey ON public.study_session USING btree (id_study_session);

CREATE UNIQUE INDEX subject_pkey ON public.subject USING btree (id_subject);

CREATE UNIQUE INDEX subject_stats_pkey ON public.subject_stats USING btree (id_subject, id_profile);

CREATE UNIQUE INDEX topic_pkey ON public.topic USING btree (id_topic);

CREATE UNIQUE INDEX topic_stats_pkey ON public.topic_stats USING btree (id_profile, id_topic);

CREATE UNIQUE INDEX userinfo_email_key ON public.userinfo USING btree (email);

CREATE UNIQUE INDEX userinfo_pkey ON public.userinfo USING btree (id_user);

CREATE UNIQUE INDEX userinfo_username_key ON public.userinfo USING btree (username);

alter table "public"."app_data" add constraint "app_data_pkey" PRIMARY KEY using index "app_data_pkey";

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."session_segment" add constraint "session_segment_pkey" PRIMARY KEY using index "session_segment_pkey";

alter table "public"."stats" add constraint "stats_pkey" PRIMARY KEY using index "stats_pkey";

alter table "public"."study_session" add constraint "study_session_pkey" PRIMARY KEY using index "study_session_pkey";

alter table "public"."subject" add constraint "subject_pkey" PRIMARY KEY using index "subject_pkey";

alter table "public"."subject_stats" add constraint "subject_stats_pkey" PRIMARY KEY using index "subject_stats_pkey";

alter table "public"."topic" add constraint "topic_pkey" PRIMARY KEY using index "topic_pkey";

alter table "public"."topic_stats" add constraint "topic_stats_pkey" PRIMARY KEY using index "topic_stats_pkey";

alter table "public"."userinfo" add constraint "userinfo_pkey" PRIMARY KEY using index "userinfo_pkey";

alter table "public"."profile" add constraint "profile_id_user_fkey" FOREIGN KEY (id_user) REFERENCES public.userinfo(id_user) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile" validate constraint "profile_id_user_fkey";

alter table "public"."session_segment" add constraint "session_segment_id_profile_fkey" FOREIGN KEY (id_profile) REFERENCES public.profile(id_profile) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."session_segment" validate constraint "session_segment_id_profile_fkey";

alter table "public"."session_segment" add constraint "session_segment_id_study_session_fkey" FOREIGN KEY (id_study_session) REFERENCES public.study_session(id_study_session) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."session_segment" validate constraint "session_segment_id_study_session_fkey";

alter table "public"."session_segment" add constraint "session_segment_id_topic_fkey" FOREIGN KEY (id_topic) REFERENCES public.topic(id_topic) not valid;

alter table "public"."session_segment" validate constraint "session_segment_id_topic_fkey";

alter table "public"."stats" add constraint "stats_id_profile_fkey" FOREIGN KEY (id_profile) REFERENCES public.profile(id_profile) not valid;

alter table "public"."stats" validate constraint "stats_id_profile_fkey";

alter table "public"."study_session" add constraint "study_session_id_profile_fkey" FOREIGN KEY (id_profile) REFERENCES public.profile(id_profile) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."study_session" validate constraint "study_session_id_profile_fkey";

alter table "public"."subject" add constraint "subject_id_profile_fkey" FOREIGN KEY (id_profile) REFERENCES public.profile(id_profile) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."subject" validate constraint "subject_id_profile_fkey";

alter table "public"."subject_stats" add constraint "subject_stats_id_profile_fkey" FOREIGN KEY (id_profile) REFERENCES public.profile(id_profile) not valid;

alter table "public"."subject_stats" validate constraint "subject_stats_id_profile_fkey";

alter table "public"."subject_stats" add constraint "subject_stats_id_subject_fkey" FOREIGN KEY (id_subject) REFERENCES public.subject(id_subject) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."subject_stats" validate constraint "subject_stats_id_subject_fkey";

alter table "public"."topic" add constraint "topic_id_subject_fkey" FOREIGN KEY (id_subject) REFERENCES public.subject(id_subject) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."topic" validate constraint "topic_id_subject_fkey";

alter table "public"."topic_stats" add constraint "topic_stats_id_profile_fkey" FOREIGN KEY (id_profile) REFERENCES public.profile(id_profile) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."topic_stats" validate constraint "topic_stats_id_profile_fkey";

alter table "public"."topic_stats" add constraint "topic_stats_id_topic_fkey" FOREIGN KEY (id_topic) REFERENCES public.topic(id_topic) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."topic_stats" validate constraint "topic_stats_id_topic_fkey";

alter table "public"."userinfo" add constraint "userinfo_email_key" UNIQUE using index "userinfo_email_key";

alter table "public"."userinfo" add constraint "userinfo_username_key" UNIQUE using index "userinfo_username_key";

grant delete on table "public"."app_data" to "anon";

grant insert on table "public"."app_data" to "anon";

grant references on table "public"."app_data" to "anon";

grant select on table "public"."app_data" to "anon";

grant trigger on table "public"."app_data" to "anon";

grant truncate on table "public"."app_data" to "anon";

grant update on table "public"."app_data" to "anon";

grant delete on table "public"."app_data" to "authenticated";

grant insert on table "public"."app_data" to "authenticated";

grant references on table "public"."app_data" to "authenticated";

grant select on table "public"."app_data" to "authenticated";

grant trigger on table "public"."app_data" to "authenticated";

grant truncate on table "public"."app_data" to "authenticated";

grant update on table "public"."app_data" to "authenticated";

grant delete on table "public"."app_data" to "postgres";

grant insert on table "public"."app_data" to "postgres";

grant references on table "public"."app_data" to "postgres";

grant select on table "public"."app_data" to "postgres";

grant trigger on table "public"."app_data" to "postgres";

grant truncate on table "public"."app_data" to "postgres";

grant update on table "public"."app_data" to "postgres";

grant delete on table "public"."app_data" to "service_role";

grant insert on table "public"."app_data" to "service_role";

grant references on table "public"."app_data" to "service_role";

grant select on table "public"."app_data" to "service_role";

grant trigger on table "public"."app_data" to "service_role";

grant truncate on table "public"."app_data" to "service_role";

grant update on table "public"."app_data" to "service_role";

grant delete on table "public"."profile" to "anon";

grant insert on table "public"."profile" to "anon";

grant references on table "public"."profile" to "anon";

grant select on table "public"."profile" to "anon";

grant trigger on table "public"."profile" to "anon";

grant truncate on table "public"."profile" to "anon";

grant update on table "public"."profile" to "anon";

grant delete on table "public"."profile" to "authenticated";

grant insert on table "public"."profile" to "authenticated";

grant references on table "public"."profile" to "authenticated";

grant select on table "public"."profile" to "authenticated";

grant trigger on table "public"."profile" to "authenticated";

grant truncate on table "public"."profile" to "authenticated";

grant update on table "public"."profile" to "authenticated";

grant delete on table "public"."profile" to "postgres";

grant insert on table "public"."profile" to "postgres";

grant references on table "public"."profile" to "postgres";

grant select on table "public"."profile" to "postgres";

grant trigger on table "public"."profile" to "postgres";

grant truncate on table "public"."profile" to "postgres";

grant update on table "public"."profile" to "postgres";

grant delete on table "public"."profile" to "service_role";

grant insert on table "public"."profile" to "service_role";

grant references on table "public"."profile" to "service_role";

grant select on table "public"."profile" to "service_role";

grant trigger on table "public"."profile" to "service_role";

grant truncate on table "public"."profile" to "service_role";

grant update on table "public"."profile" to "service_role";

grant delete on table "public"."session_segment" to "anon";

grant insert on table "public"."session_segment" to "anon";

grant references on table "public"."session_segment" to "anon";

grant select on table "public"."session_segment" to "anon";

grant trigger on table "public"."session_segment" to "anon";

grant truncate on table "public"."session_segment" to "anon";

grant update on table "public"."session_segment" to "anon";

grant delete on table "public"."session_segment" to "authenticated";

grant insert on table "public"."session_segment" to "authenticated";

grant references on table "public"."session_segment" to "authenticated";

grant select on table "public"."session_segment" to "authenticated";

grant trigger on table "public"."session_segment" to "authenticated";

grant truncate on table "public"."session_segment" to "authenticated";

grant update on table "public"."session_segment" to "authenticated";

grant delete on table "public"."session_segment" to "postgres";

grant insert on table "public"."session_segment" to "postgres";

grant references on table "public"."session_segment" to "postgres";

grant select on table "public"."session_segment" to "postgres";

grant trigger on table "public"."session_segment" to "postgres";

grant truncate on table "public"."session_segment" to "postgres";

grant update on table "public"."session_segment" to "postgres";

grant delete on table "public"."session_segment" to "service_role";

grant insert on table "public"."session_segment" to "service_role";

grant references on table "public"."session_segment" to "service_role";

grant select on table "public"."session_segment" to "service_role";

grant trigger on table "public"."session_segment" to "service_role";

grant truncate on table "public"."session_segment" to "service_role";

grant update on table "public"."session_segment" to "service_role";

grant delete on table "public"."stats" to "anon";

grant insert on table "public"."stats" to "anon";

grant references on table "public"."stats" to "anon";

grant select on table "public"."stats" to "anon";

grant trigger on table "public"."stats" to "anon";

grant truncate on table "public"."stats" to "anon";

grant update on table "public"."stats" to "anon";

grant delete on table "public"."stats" to "authenticated";

grant insert on table "public"."stats" to "authenticated";

grant references on table "public"."stats" to "authenticated";

grant select on table "public"."stats" to "authenticated";

grant trigger on table "public"."stats" to "authenticated";

grant truncate on table "public"."stats" to "authenticated";

grant update on table "public"."stats" to "authenticated";

grant delete on table "public"."stats" to "postgres";

grant insert on table "public"."stats" to "postgres";

grant references on table "public"."stats" to "postgres";

grant select on table "public"."stats" to "postgres";

grant trigger on table "public"."stats" to "postgres";

grant truncate on table "public"."stats" to "postgres";

grant update on table "public"."stats" to "postgres";

grant delete on table "public"."stats" to "service_role";

grant insert on table "public"."stats" to "service_role";

grant references on table "public"."stats" to "service_role";

grant select on table "public"."stats" to "service_role";

grant trigger on table "public"."stats" to "service_role";

grant truncate on table "public"."stats" to "service_role";

grant update on table "public"."stats" to "service_role";

grant delete on table "public"."study_session" to "anon";

grant insert on table "public"."study_session" to "anon";

grant references on table "public"."study_session" to "anon";

grant select on table "public"."study_session" to "anon";

grant trigger on table "public"."study_session" to "anon";

grant truncate on table "public"."study_session" to "anon";

grant update on table "public"."study_session" to "anon";

grant delete on table "public"."study_session" to "authenticated";

grant insert on table "public"."study_session" to "authenticated";

grant references on table "public"."study_session" to "authenticated";

grant select on table "public"."study_session" to "authenticated";

grant trigger on table "public"."study_session" to "authenticated";

grant truncate on table "public"."study_session" to "authenticated";

grant update on table "public"."study_session" to "authenticated";

grant delete on table "public"."study_session" to "postgres";

grant insert on table "public"."study_session" to "postgres";

grant references on table "public"."study_session" to "postgres";

grant select on table "public"."study_session" to "postgres";

grant trigger on table "public"."study_session" to "postgres";

grant truncate on table "public"."study_session" to "postgres";

grant update on table "public"."study_session" to "postgres";

grant delete on table "public"."study_session" to "service_role";

grant insert on table "public"."study_session" to "service_role";

grant references on table "public"."study_session" to "service_role";

grant select on table "public"."study_session" to "service_role";

grant trigger on table "public"."study_session" to "service_role";

grant truncate on table "public"."study_session" to "service_role";

grant update on table "public"."study_session" to "service_role";

grant delete on table "public"."subject" to "anon";

grant insert on table "public"."subject" to "anon";

grant references on table "public"."subject" to "anon";

grant select on table "public"."subject" to "anon";

grant trigger on table "public"."subject" to "anon";

grant truncate on table "public"."subject" to "anon";

grant update on table "public"."subject" to "anon";

grant delete on table "public"."subject" to "authenticated";

grant insert on table "public"."subject" to "authenticated";

grant references on table "public"."subject" to "authenticated";

grant select on table "public"."subject" to "authenticated";

grant trigger on table "public"."subject" to "authenticated";

grant truncate on table "public"."subject" to "authenticated";

grant update on table "public"."subject" to "authenticated";

grant delete on table "public"."subject" to "postgres";

grant insert on table "public"."subject" to "postgres";

grant references on table "public"."subject" to "postgres";

grant select on table "public"."subject" to "postgres";

grant trigger on table "public"."subject" to "postgres";

grant truncate on table "public"."subject" to "postgres";

grant update on table "public"."subject" to "postgres";

grant delete on table "public"."subject" to "service_role";

grant insert on table "public"."subject" to "service_role";

grant references on table "public"."subject" to "service_role";

grant select on table "public"."subject" to "service_role";

grant trigger on table "public"."subject" to "service_role";

grant truncate on table "public"."subject" to "service_role";

grant update on table "public"."subject" to "service_role";

grant delete on table "public"."subject_stats" to "anon";

grant insert on table "public"."subject_stats" to "anon";

grant references on table "public"."subject_stats" to "anon";

grant select on table "public"."subject_stats" to "anon";

grant trigger on table "public"."subject_stats" to "anon";

grant truncate on table "public"."subject_stats" to "anon";

grant update on table "public"."subject_stats" to "anon";

grant delete on table "public"."subject_stats" to "authenticated";

grant insert on table "public"."subject_stats" to "authenticated";

grant references on table "public"."subject_stats" to "authenticated";

grant select on table "public"."subject_stats" to "authenticated";

grant trigger on table "public"."subject_stats" to "authenticated";

grant truncate on table "public"."subject_stats" to "authenticated";

grant update on table "public"."subject_stats" to "authenticated";

grant delete on table "public"."subject_stats" to "postgres";

grant insert on table "public"."subject_stats" to "postgres";

grant references on table "public"."subject_stats" to "postgres";

grant select on table "public"."subject_stats" to "postgres";

grant trigger on table "public"."subject_stats" to "postgres";

grant truncate on table "public"."subject_stats" to "postgres";

grant update on table "public"."subject_stats" to "postgres";

grant delete on table "public"."subject_stats" to "service_role";

grant insert on table "public"."subject_stats" to "service_role";

grant references on table "public"."subject_stats" to "service_role";

grant select on table "public"."subject_stats" to "service_role";

grant trigger on table "public"."subject_stats" to "service_role";

grant truncate on table "public"."subject_stats" to "service_role";

grant update on table "public"."subject_stats" to "service_role";

grant delete on table "public"."topic" to "anon";

grant insert on table "public"."topic" to "anon";

grant references on table "public"."topic" to "anon";

grant select on table "public"."topic" to "anon";

grant trigger on table "public"."topic" to "anon";

grant truncate on table "public"."topic" to "anon";

grant update on table "public"."topic" to "anon";

grant delete on table "public"."topic" to "authenticated";

grant insert on table "public"."topic" to "authenticated";

grant references on table "public"."topic" to "authenticated";

grant select on table "public"."topic" to "authenticated";

grant trigger on table "public"."topic" to "authenticated";

grant truncate on table "public"."topic" to "authenticated";

grant update on table "public"."topic" to "authenticated";

grant delete on table "public"."topic" to "postgres";

grant insert on table "public"."topic" to "postgres";

grant references on table "public"."topic" to "postgres";

grant select on table "public"."topic" to "postgres";

grant trigger on table "public"."topic" to "postgres";

grant truncate on table "public"."topic" to "postgres";

grant update on table "public"."topic" to "postgres";

grant delete on table "public"."topic" to "service_role";

grant insert on table "public"."topic" to "service_role";

grant references on table "public"."topic" to "service_role";

grant select on table "public"."topic" to "service_role";

grant trigger on table "public"."topic" to "service_role";

grant truncate on table "public"."topic" to "service_role";

grant update on table "public"."topic" to "service_role";

grant delete on table "public"."topic_stats" to "anon";

grant insert on table "public"."topic_stats" to "anon";

grant references on table "public"."topic_stats" to "anon";

grant select on table "public"."topic_stats" to "anon";

grant trigger on table "public"."topic_stats" to "anon";

grant truncate on table "public"."topic_stats" to "anon";

grant update on table "public"."topic_stats" to "anon";

grant delete on table "public"."topic_stats" to "authenticated";

grant insert on table "public"."topic_stats" to "authenticated";

grant references on table "public"."topic_stats" to "authenticated";

grant select on table "public"."topic_stats" to "authenticated";

grant trigger on table "public"."topic_stats" to "authenticated";

grant truncate on table "public"."topic_stats" to "authenticated";

grant update on table "public"."topic_stats" to "authenticated";

grant delete on table "public"."topic_stats" to "postgres";

grant insert on table "public"."topic_stats" to "postgres";

grant references on table "public"."topic_stats" to "postgres";

grant select on table "public"."topic_stats" to "postgres";

grant trigger on table "public"."topic_stats" to "postgres";

grant truncate on table "public"."topic_stats" to "postgres";

grant update on table "public"."topic_stats" to "postgres";

grant delete on table "public"."topic_stats" to "service_role";

grant insert on table "public"."topic_stats" to "service_role";

grant references on table "public"."topic_stats" to "service_role";

grant select on table "public"."topic_stats" to "service_role";

grant trigger on table "public"."topic_stats" to "service_role";

grant truncate on table "public"."topic_stats" to "service_role";

grant update on table "public"."topic_stats" to "service_role";

grant delete on table "public"."userinfo" to "anon";

grant insert on table "public"."userinfo" to "anon";

grant references on table "public"."userinfo" to "anon";

grant select on table "public"."userinfo" to "anon";

grant trigger on table "public"."userinfo" to "anon";

grant truncate on table "public"."userinfo" to "anon";

grant update on table "public"."userinfo" to "anon";

grant delete on table "public"."userinfo" to "authenticated";

grant insert on table "public"."userinfo" to "authenticated";

grant references on table "public"."userinfo" to "authenticated";

grant select on table "public"."userinfo" to "authenticated";

grant trigger on table "public"."userinfo" to "authenticated";

grant truncate on table "public"."userinfo" to "authenticated";

grant update on table "public"."userinfo" to "authenticated";

grant delete on table "public"."userinfo" to "postgres";

grant insert on table "public"."userinfo" to "postgres";

grant references on table "public"."userinfo" to "postgres";

grant select on table "public"."userinfo" to "postgres";

grant trigger on table "public"."userinfo" to "postgres";

grant truncate on table "public"."userinfo" to "postgres";

grant update on table "public"."userinfo" to "postgres";

grant delete on table "public"."userinfo" to "service_role";

grant insert on table "public"."userinfo" to "service_role";

grant references on table "public"."userinfo" to "service_role";

grant select on table "public"."userinfo" to "service_role";

grant trigger on table "public"."userinfo" to "service_role";

grant truncate on table "public"."userinfo" to "service_role";

grant update on table "public"."userinfo" to "service_role";


